[project]
name = "github-management"
version = "1.0.0"
description = "Python tool for managing GitHub organizations and repositories."
authors = [{ name = "albr21" }]
dependencies = [
    "PyGitHub>=2.9.1",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
